### ISSUE TITLE
Can't upgrade Sentries below with iPad

### ISSUE THREAD

**Issue by gofeel** [getsentry/sentry-defenses#10]
### Environment

Apple M1 mac

### Steps to Reproduce

check the video

### Expected Result

Clickable sentries

### Actual Result
https://user-images.githubusercontent.com/1040675/139394830-4a5e9702-7c1b-4cfd-ad23-e5a37561813c.mov

It's hidden by buttons :(

**Comment by gofeel** [comment]
I think it would be better to reduce the battle area or resize and move buttons to bottom. I want to make a PR but unfortunately I have no time to do that :( (and I am not familiar with Unity.)

**Comment by bitsandfoxes** [comment]
Hey @gofeel! Thanks for raising this. Your suggestion totally makes sense. I'm surprised we didn't notice that sooner! I'll look into it.

**Comment by bruno-garcia** [comment]
We haven't had a chance to change this yet but if you feel like making the change and opening a PR, we're happy to merge

**Comment by bitsandfoxes** [comment]
With the recent changes to the game mechanics this should no longer be an issue!

**Comment by bruno-garcia** [comment]
Please let us know if this is still an issue
